// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QL_BangKiem_KhaoSat.Data;

#nullable disable

namespace QL_BangKiem_KhaoSat.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250703205044_Step")]
    partial class Step
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QL_BangKiem_KhaoSat.Models.BangKiemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DieuDuongThucHien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Khoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayGiamSat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiGiamSat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhomThaoTacJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenForm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BangKiemEntities");
                });

            modelBuilder.Entity("QL_BangKiem_KhaoSat.Models.BangKiemStepResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BangKiemEntityId")
                        .HasColumnType("int");

                    b.Property<float?>("Diem")
                        .HasColumnType("real");

                    b.Property<string>("KetQuaLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("KetQuaNhom1")
                        .HasColumnType("real");

                    b.Property<float?>("KetQuaNhom2")
                        .HasColumnType("real");

                    b.Property<string>("LoaiKetQua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StepIndex")
                        .HasColumnType("int");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BangKiemEntityId");

                    b.ToTable("BangKiemStepResults");
                });

            modelBuilder.Entity("QL_BangKiem_KhaoSat.Models.BangKiemSubStepResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BangKiemStepResultId")
                        .HasColumnType("int");

                    b.Property<float?>("Diem")
                        .HasColumnType("real");

                    b.Property<float?>("KetQuaNhom1")
                        .HasColumnType("real");

                    b.Property<float?>("KetQuaNhom2")
                        .HasColumnType("real");

                    b.Property<int>("StepResultId")
                        .HasColumnType("int");

                    b.Property<string>("SubStepName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BangKiemStepResultId");

                    b.ToTable("BangKiemSubStepResults");
                });

            modelBuilder.Entity("QL_BangKiem_KhaoSat.Models.KhoaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Khoas");
                });

            modelBuilder.Entity("QL_BangKiem_KhaoSat.Models.LichSuDuyetEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LichSuDuyets");
                });

            modelBuilder.Entity("QL_BangKiem_KhaoSat.Models.StepEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FormKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("StepIndex")
                        .HasColumnType("int");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StepEntities");
                });

            modelBuilder.Entity("QL_BangKiem_KhaoSat.Models.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaDuyet")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<int>("VaiTroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VaiTroId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QL_BangKiem_KhaoSat.Models.VaiTroEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VaiTros");
                });

            modelBuilder.Entity("QL_BangKiem_KhaoSat.Models.BangKiemStepResult", b =>
                {
                    b.HasOne("QL_BangKiem_KhaoSat.Models.BangKiemEntity", "BangKiem")
                        .WithMany("KetQua")
                        .HasForeignKey("BangKiemEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BangKiem");
                });

            modelBuilder.Entity("QL_BangKiem_KhaoSat.Models.BangKiemSubStepResult", b =>
                {
                    b.HasOne("QL_BangKiem_KhaoSat.Models.BangKiemStepResult", "BangKiemStepResult")
                        .WithMany("SubSteps")
                        .HasForeignKey("BangKiemStepResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BangKiemStepResult");
                });

            modelBuilder.Entity("QL_BangKiem_KhaoSat.Models.LichSuDuyetEntity", b =>
                {
                    b.HasOne("QL_BangKiem_KhaoSat.Models.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QL_BangKiem_KhaoSat.Models.UserEntity", b =>
                {
                    b.HasOne("QL_BangKiem_KhaoSat.Models.VaiTroEntity", "VaiTro")
                        .WithMany()
                        .HasForeignKey("VaiTroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("QL_BangKiem_KhaoSat.Models.BangKiemEntity", b =>
                {
                    b.Navigation("KetQua");
                });

            modelBuilder.Entity("QL_BangKiem_KhaoSat.Models.BangKiemStepResult", b =>
                {
                    b.Navigation("SubSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
